#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "wgdashboard"
name = "WGDashboard"
description.en = "A WireGuard Dashboard for more control"

version = "4.2.4~ynh1"

maintainers = ["botagas"]

[upstream]
license = "GPL-3.0-or-later"
website = "https://wgdashboard.dev"
code = "https://github.com/donaldzou/WGDashboard"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = false
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/example"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/donaldzou/WGDashboard/archive/refs/tags/v4.2.4.tar.gz"
    sha256 = "a0138d10aba075b9a207f583fd059d878b40a00e2fb6278f6adfc5991d63dcbc"

    autoupdate.strategy = "latest_github_tag"

    [resources.system_user]
    home = "/var/www/wgdashboard"

    [resources.install_dir]
    dir = "/var/www/wgdashboard"

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main_tcp.default = 10086
    main_udp.default = 51820
    main_udp.exposed = "UDP"

    [resources.apt]
    packages = ["wireguard-tools", "net-tools", "python3-venv", "python3-dev", "python3-pip"]
